### ISSUE TITLE
Span tag For Applied Job are Not Processed and Undefined Variable

### ISSUE THREAD

**Issue by himanshuahuja96** [Automattic/WP-Job-Manager#1169]
#### What I Expected To Happen
1) If A user created and he has self applied then HTML TAGS Must be Processed at at Jobs,Job Dashboard Page
2) There should not be any Undefined Variable error 
#### What Happened Instead
1) If A user created and he has self applied then HTML TAGS WONT Process at all at Job Dashboard Page
2) Undefined variable: application_ids in wp-content\plugins\wp-job-manager-applications\includes\class-wp-job-manager-applications-post-types.php on line 190
Enable WP_Debug and See there is Undefined variable error at When Employeer reviews and Add comment after that it gives this error.
#### Steps to Reproduce the Bug
-------------------------------------------------------------------
**HTML Tags Not Processing**
1)create job and apply for same
2) Go to Jobs and Jobs Dashboard Page and see there is  `<span class="job-manager-applications-applied-notice">Applied</span>` is not processed
------------------------------------------------------------------
**Undefined Variable Error**
Enable WP Debug
1)Goto Job dashboard page and Click on number of applications.
2) Then give user review and change its to Some thing Interviewed or else
3)There will be undefined variable error there.

![Alt text](https://i.imgur.com/imm4P6n.png "Optional title")

**Comment by jom** [comment]
This should be fixed when running the most recent version of our add-ons. We'll make sure we update our demo site. Thank you!

**Comment by innocuous** [comment]
Its not fixed..I am running WP Job Manager Version 1.28.0 and the above is still showing 
How do we fix?

**Comment by jom** [comment]
This wasn't fixed through an update to WP Job Manager core plugin. You'll need the most up-to-date version of _WP Job Manager - Applications_ (2.2.6).

**Comment by innocuous** [comment]
Ok thanks

**Comment by innocuous** [comment]
If we don't use the paid applications plugin then?

**Comment by jom** [comment]
Then you'll need to track down the source of the message. If it was bundled with a theme, it'll need to be updated. 

This is just for WPJM core issues.
