### ISSUE TITLE
Format Broken After Job Saved as Draft

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1775]
#### Steps to Reproduce
1. Jobify Theme
2. WPJM 1.33.0
3. WP Fied Editor by Smyles

#### What I Expected
On Job Submission form I have two Text Area( Using WP Field Editor) Roles & Responsibilities and Required Knowledge & Skills.
Filled that two fields with formated paragraph
Job Saved as a Draft
When Reopen and continue the job form, all format should be in place and saved format.

#### What Happened Instead
When Reopen and continue the job form, found that two fields paragraph are merged into a single paragraph and no formating intact.("Bulleted all fields are got merged and shown all in one paragraph)

#### WordPress / WP Job Manager Version
Latest all

#### Browser / OS Version
Crome, Mozilla & Suffari

#### Screenshot / Video

http://prntscr.com/ny8fc8

**Comment by thedigitalcircle** [comment]
Hi!!
Continuation of the above...
After reformatting the changes, it will never taking effect on those fields again.
Shuvashish

**Comment by jom** [comment]
> The Save Draft Option is also Bypassing the Google Recaptcha option.

Thanks for the report. I'll move this into a new issue.

**Comment by Dubaidogfish** [comment]
Yes I see in jobify it removes the formatting (paragraphs), from Company Details - Description field, only editing in backend after front end submission fixes it. (another error 1.33 caused with jobify seems to relate to the Company Profiles plugin no longer finding jobs from that company and instead showing a single featured job from another company)

**Comment by jom** [comment]
This WP Editor custom field issue was fixed by #1777. Feel free to test in [1.33.1](https://github.com/Automattic/WP-Job-Manager/releases/tag/1.33.1-beta.1)--should be released today.

**Comment by Dubaidogfish** [comment]
That beta fixes both the description and the Company Profiles results. 

Search by region still broken but raised that there https://github.com/Astoundify/wp-job-manager-regions/issues/74 .
